/*
 * Copyright (c) 2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { SongData } from '../model/SongData';

export const  songDataList: SongData[] = [{
  id: 1,
  title: 'Dream It Possible',
  singer: 'Delacey',
  label: $r('app.media.ic_dream'),
  src: 'Delacey - Dream It Possible',
  index: 0,
  isDarkBackground: true,
  mark: $r('app.media.ic_vip')
}];

export enum AudioName {
  PCM = '.pcm'
}

export enum VolumeType {
  AUDIOSTREAM = 1
}

export const imageList: ResourceStr[] = [
  $r('app.media.ic_public_play'),
  $r('app.media.ic_public_pause')
]